import MathQuill from 'src/publicapi';
window.MathQuill = MathQuill;

import 'test/html.test';
import 'test/text.test';
import 'test/typing.test';
import 'test/updown.test';
import 'test/saneKeyboardEvents.test';
import 'test/latex.test';
import 'test/parser.test';
import 'test/autoOperatorNames.test';
import 'test/backspace.test';
import 'test/css.test';
import 'test/publicapi.test';
import 'test/autosubscript.test';
import 'test/select.test';
import 'test/tree.test';
import 'test/focusBlur.test';
import 'test/SupSub.test';
import 'test/MathFunction.test';
